# Lesson 2 Practice: NumPy Part 2
Use this notebook to follow along with the lesson in the corresponding lesson notebook: [L02-Numpy_Part2-Lesson.ipynb](./L02-Numpy_Part2-Lesson.ipynb).  


## Instructions
Follow along with the teaching material in the lesson. Throughout the tutorial sections labeled as "Tasks" are interspersed and indicated with the icon: ![Task](http://icons.iconarchive.com/icons/sbstnblnd/plateau/16/Apps-gnome-info-icon.png). You should follow the instructions provided in these sections by performing them in the practice notebook.  When the tutorial is completed you can turn in the final practice notebook. For each task, use the cell below it to write and test your code.  You may add additional cells for any task as needed or desired. 

## Task 1a: Setup

In the practice notebook, import the following packages:
+ `numpy` as `np`

In [2]:
import numpy as np

## Task 2a: Indexing by Subsetting and Slicing

In the practice notebook perform the following:

1. Create (or re-use) 3 arrays, each containing three dimensions.
2. Slice each of these arrays so that:
    + One element / number is returned.
    + One dimension is returned.
    + A subset of a dimension is returned.
3. What is the difference between `[x:]` and `[x, ...]`? (hint, try each on high-dimension arrays).
    
*Exactly what you choose to return is not imporant at this point, the goal of this task is to train you so that if you are given an n-dimension NumPy array, you can write an index or slice that returns a subset of desired positions.*

In [38]:
array1 = np.array((([2,4,6,8], [1,3,5,7], [2,3,4,5])))
array2 = np.array((([5,6,7,8], [1,2,3,4], [1,5,6,7])))
array3 = np.array((([8,6,5,7], [4,2,1,3], [8,3,4,7])))
array4 = np.random.random((8,8))
print(array1)
print(array2)
print(array3)
print(array4)

array1[-1,-1]
array2[0:1]
array3[0:2]
array4[2:6]
array4[2,6]




[[2 4 6 8]
 [1 3 5 7]
 [2 3 4 5]]
[[5 6 7 8]
 [1 2 3 4]
 [1 5 6 7]]
[[8 6 5 7]
 [4 2 1 3]
 [8 3 4 7]]
[[0.92134999 0.15860119 0.64729405 0.64195978 0.57598358 0.08947654
  0.25968194 0.22989045]
 [0.05399175 0.67006573 0.20761091 0.07051874 0.03476139 0.12783371
  0.26859574 0.54160746]
 [0.63325167 0.56844001 0.15316747 0.9843632  0.72026618 0.10346359
  0.29930055 0.82113425]
 [0.13145359 0.76610115 0.12586894 0.15168428 0.00377479 0.92160516
  0.89824596 0.7975289 ]
 [0.93669963 0.2647959  0.99133585 0.89854105 0.35236676 0.59764552
  0.42898415 0.45879199]
 [0.31288194 0.0293622  0.13245467 0.19293174 0.25403078 0.8121152
  0.94947734 0.33009633]
 [0.98557878 0.39957141 0.04955396 0.24638506 0.01053765 0.89062956
  0.20450107 0.02341285]
 [0.10309193 0.21116617 0.04274684 0.76997023 0.08688188 0.15217951
  0.87961408 0.78173498]]


0.29930055116637566

## Task 3a: Boolean Indexing

In the practice notebook perform the following:

+ Experiment with the following boolean conditionals to generate boolean arrays for indexing:
  + Greater than
  + Less than
  + Equals
  + Combine two or more of the above with:
      + or `|`
      + and `&`

You can create arrays or use existing ones

In [34]:
array1 = np.array(([2,4,6,8], [1,3,5,7]))
array2 = np.array(([5,6,7,8], [1,2,3,4]))
array3 = np.array(([8,6,5,7], [4,2,1,3]))

array1 > 5
array2 < 5
array3 == 5
array1 == 5&8
array2 > 3|4



array([[False, False, False,  True],
       [False, False, False, False]])

## Task 4a: Getting Help

In the practice notebook perform the following:

+ In the code cell below, call `help()` on two of the following functions: `np.transpose()`, `np.reshape()`, `np.resize()`, `np.ravel()`, `np.append()`, `np.delete()`, `np.concatenate()`, `np.vstack()`, `np.hstack()`, `np.column_stack()`, `np.vsplit()`, `np.hsplit()` 
+ Respond to this question: Did you understand the help docuemntation? Could you use the function just by looking at what the help says about it?  

In [25]:
help(np.transpose)
help(np.delete)
help(np.append)

#I was mostly able to understand it, althought some of the terminology is still confusing.  I would be able to work 
#through using the function with the example given.

Help on function transpose in module numpy:

transpose(a, axes=None)
    Permute the dimensions of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axes : list of ints, optional
        By default, reverse the dimensions, otherwise permute the axes
        according to the values given.
    
    Returns
    -------
    p : ndarray
        `a` with its axes permuted.  A view is returned whenever
        possible.
    
    See Also
    --------
    moveaxis
    argsort
    
    Notes
    -----
    Use `transpose(a, argsort(axes))` to invert the transposition of tensors
    when using the `axes` keyword argument.
    
    Transposing a 1-D array returns an unchanged view of the original array.
    
    Examples
    --------
    >>> x = np.arange(4).reshape((2,2))
    >>> x
    array([[0, 1],
           [2, 3]])
    
    >>> np.transpose(x)
    array([[0, 2],
           [1, 3]])
    
    >>> x = np.ones((1, 2, 3))
    >>> np.transpose(x, (1, 0, 2)).s

## Task 5a: Transposing an Array

In the practice notebook perform the following:

+ Create a matrix of any size and transpose it.

In [40]:
array5 = np.ones((2,3))
print(array5)
np.transpose(array5)

[[1. 1. 1.]
 [1. 1. 1.]]


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## Task 5b: Reshaping an Array

In the practice notebook peform the following:

+ Create a matrix and resize it by adding 2 extra columns
+ Create a matrix and resize it by adding 1 extra row
+ Create a matrix of 8 x 2 and resize it to 4 x 4

In [10]:
z = np.array(([1,2,3,4], [5,6,7,8]))
print(z)
np.resize(z, (2,6))

a = np.array(([1,2,3,4], [5,6,7,8]))
print(a)
np.resize(z, (3,4))

b = np.ones((8,2))
print(b)
print(b.reshape((4,4)))

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Task 5c: Appending to an Array

In the practice notebook perform the following:

 + Create a three dimensional array and append another row to the array
 + Append another colum to the array
 + Print the final results

In [4]:
c = np.array((([2,4,6,8], [1,3,5,7], [2,3,4,5])))
print(c)
newc = np.append(c, [[4,5,6,7]], axis=0)
print(newc)
newerc = np.append(newc, [[2], [3], [4], [5]], axis=1)
print(newerc)

[[2 4 6 8]
 [1 3 5 7]
 [2 3 4 5]]
[[2 4 6 8]
 [1 3 5 7]
 [2 3 4 5]
 [4 5 6 7]]
[[2 4 6 8 2]
 [1 3 5 7 3]
 [2 3 4 5 4]
 [4 5 6 7 5]]


## Task 5d: Inserting and Deleting Elements

In the practice notebook perform the following:

+ Examine the `help()` documentation for how to use the `insert()` and `delete()` functions.
+ Create a matrix and practice inserting a row and deleting a column.

In [3]:

array6 = np.array((([2,4,6,8], [1,3,5,7], [2,3,4,5])))
print(array6)
newarray6 = np.insert(array6, 2, 5, axis=1)
print(newarray6)
newerarray6 = np.delete(newarray6, 2, 0)
print(newerarray6)

[[2 4 6 8]
 [1 3 5 7]
 [2 3 4 5]]
[[2 4 5 6 8]
 [1 3 5 5 7]
 [2 3 5 4 5]]
[[2 4 5 6 8]
 [1 3 5 5 7]]


## Task 5e: Joining Arrays

In the practice notebook perform the following:

+ Execute the code (in the cell below).
+ Examine the output from each of the function calls in the cell above. If needed to understand, review the help pages for each tool either using the `help()` command or the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html). 
+ Respond to the following question and respond in the second cell below.
  + Can you identify what is happening with each of them?

In [60]:
# Concatentate `my_array` and `x`: similar to np.append()
my_array = np.array([1,2,3,4])
x = np.array([1,1,1,1])
print("concatenate:")
print(np.concatenate((my_array, x)))

# Stack arrays row-wise
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("\nvstack:")
print(np.vstack((my_array, my_2d_array)))

# Stack arrays horizontally
print("\nhstack:")
print(np.hstack((my_2d_array, my_2d_array)))

# Stack arrays column-wise
print("\ncolumn_stack:")
print(np.column_stack((my_2d_array, my_2d_array)))

concatenate:
[1 2 3 4 1 1 1 1]

vstack:
[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]]

hstack:
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]

column_stack:
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]


## Task 5d: Splitting Arrays

In the practice notebook perform the following:

+ Execute the code (as shown below).
+ Examine the output from each of the function calls in the cell above. If needed to understand, review the help pages for each tool either using the `help()` command or the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html). 
+ Respond to the following question and respond in the second cell below.
  + Can you identify what is happening with each of them?

In [61]:
# Create a 2D array.
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("original:")
print(my_2d_array)

# Split `my_stacked_array` horizontally at the 2nd index
print("\nhsplit:")
print(np.hsplit(my_2d_array, 2))

# Split `my_stacked_array` vertically at the 2nd index
print("\nvsplit:")
print(np.vsplit(my_2d_array, 2))

original:
[[1 2 3 4]
 [5 6 7 8]]

hsplit:
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]

vsplit:
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
