# Lesson 1 Practice: NumPy Part 1
Use this notebook to follow along with the lesson in the corresponding lesson notebook: [L01-Numpy_Part1-Lesson.ipynb](./L01-Numpy_Part1-Lesson.ipynb).  



## Instructions
Follow along with the teaching material in the lesson. Throughout the tutorial sections labeled as "Tasks" are interspersed and indicated with the icon: ![Task](http://icons.iconarchive.com/icons/sbstnblnd/plateau/16/Apps-gnome-info-icon.png). You should follow the instructions provided in these sections by performing them in the practice notebook.  When the tutorial is completed you can turn in the final practice notebook. For each task, use the cell below it to write and test your code.  You may add additional cells for any task as needed or desired.  

## Task 1a: Setup

In the practice notebook, import the following packages:
+ `numpy` as `np`

In [1]:
import numpy as np

## Task 2a: Creating Arrays

In the practice notebook, perform the following.  
- Create a 1-dimensional numpy array and print it.
- Create a 2-dimensional numpy array and print it.
- Create a 3-dimensional numpy array and print it.

In [4]:
my_array = np.array([1,3,5,7])
my_2d_array = np.array([[1,3,5,7], [2,4,6,8]])
my_3d_array = np.array([[[1,3,5,7], [2,4,6,8], [3,4,5,6]]])
print(my_array)
print(my_2d_array)
print(my_3d_array)

[1 3 5 7]
[[1 3 5 7]
 [2 4 6 8]]
[[[1 3 5 7]
  [2 4 6 8]
  [3 4 5 6]]]


## Task 3a: Accessing Array Attributes

In the practice notebook, perform the following.

- Create a NumPy array.
- Write code that prints these attributes (one per line): `ndim`, `shape`, `size`, `dtype`, `itemsize`, `data`, `nbytes`.
- Add a comment line, before each line describing what value the attribute returns. 


In [6]:
my_array = np.array([[1,2,3,4], [5,6,7,8]])

print(my_array)
#Prints the number of dimensions for the array
print(my_array.ndim)
#Prints the rows and columns of the array
print(my_array.shape)
#Prints the amount of elements in the array
print(my_array.size)
#Prints the data type of the array
print(my_array.dtype)
#Prints the length of one array in the array
print(my_array.itemsize)
#Prints a buffer for the array(What does this mean?)
print(my_array.data)
#Prints the number of bytes of the array
print(my_array.nbytes)


[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
8
int32
4
32


## Task 4a: Initializing Arrays

In the practice notebook, perform the following.

+ Create an initialized array by using these functions:  `ones`, `zeros`, `empty`, `full`, `arange`, `linspace` and `random.random`. Be sure to follow each array creation with a call to `print()` to display your newly created arrays. 
+ Add a comment above each function call describing what is being done.  

In [29]:
#Prints an array of all ones
ones = np.ones((2,3))
#Prints an array of all zeros
zeros = np.zeros((2,3))
#Prints an empty array
empty = np.empty((2,3))
#Prints an array of the specified number
full = np.full((2,3), 7)
#Prints the number within the specified range
arange = np.arange(2, 7)
#Prints the numbers specified spaced out evenly by what num equals
linspace = np.linspace(2.0, 7.0, num=5)
#Prints a random array of numbers between 0 and 1
random = np.random.random((5)) 


print(ones)
print(zeros)
print(empty)
print(full)
print(arange)
print(linspace)
print(random)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[7 7 7]
 [7 7 7]]
[2 3 4 5 6]
[2.   3.25 4.5  5.75 7.  ]
[0.16038049 0.31851352 0.54988664 0.92809141 0.41453737]


## Task 5a:  Broadcasting Arrays

In the practice notebook, perform the following.

+ Create two arrays of differing sizes but compatible with broadcasting.
+ Perform addition, multiplication and subtraction.
+ Create two additional arrays of differing size that do not meet the rules for broadcasting and try a mathematical operation.  

In [8]:
example_a = np.ones((2,3))
example_b = np.random.random((3))

print(f"example_a shape: {example_a.shape}")
print(f"example_b shape: {example_b.shape}")

print(example_a)
print(example_b)

result1 = example_a + example_b
result2 = example_a - example_b
result3 = example_a * example_b

print(result1)
print(result2)
print(result3)

example_c = np.ones((2,3))
example_d = np.random.random((4,5))

print(f"example_c shape: {example_c.shape}")
print(f"example_d shape: {example_d.shape}")

print(example_c)
print(example_d)

result4 = example_c + example_d
print(result4)



example_a shape: (2, 3)
example_b shape: (3,)
[[1. 1. 1.]
 [1. 1. 1.]]
[0.34896737 0.13781869 0.95488657]
[[1.34896737 1.13781869 1.95488657]
 [1.34896737 1.13781869 1.95488657]]
[[0.65103263 0.86218131 0.04511343]
 [0.65103263 0.86218131 0.04511343]]
[[0.34896737 0.13781869 0.95488657]
 [0.34896737 0.13781869 0.95488657]]
example_c shape: (2, 3)
example_d shape: (4, 5)
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.2393335  0.27618794 0.09027583 0.64610441 0.08402901]
 [0.53565464 0.56374073 0.60175771 0.04062084 0.51676744]
 [0.69703523 0.74498024 0.46917886 0.93720184 0.00647366]
 [0.16542833 0.25903927 0.85202083 0.73657518 0.1861299 ]]


ValueError: operands could not be broadcast together with shapes (2,3) (4,5) 

## Task 6a: Math/Stats Aggregate Functions

In the practice notebook, perform the following.

+ Create three to five arrays
+ Experiment with each of the aggregation functions: `sum`, `minimum`, `maximum`, `cumsum`, `mean`, `np.corrcoef`, `np.std`, `np.var`. 
+ For each function call, add a comment line above it that describes what it does.  
```


In [23]:
array1 = [1,2,3,4]
array2 = [4,5,6,7]
array3 = [4,3,2,1]

#Sums the elements of the provided array
np.sum(array1)
#Takes two or more arrays and returns an array of the smallest element in each place
np.minimum(array3, array1)
#Takes two or more arrays and returns an array of the largest element in each place
np.maximum(array3, array1)
#Takes the total sum of the array and returns a data type
np.cumsum(array1)
#Takes the mean of the array
np.mean(array2)
#Takes arrays and returns correlation coefficient
np.corrcoef(array1, array3)
#Takes the standard deviation of the array
np.std(array1)
#Takes the variance of the array
np.var(array2)

1.25

## Task 6b: Logical Aggregate Functions

In the practice notebook, perform the following.

+ Create two arrays containing boolean values.
+ Experiment with each of the aggregation functions: `logical_and`, `logical_or`, `logical_not`. 
+ For each function call, add a comment line above it that describes what it does.  
```

In [27]:
a = [True, False, True, False]
b = [False, False, True, True]

#Takes both arrays and peforms an And logic test with them
np.logical_and(a,b)
#Takes both arrays and performs an Or logic test with them
np.logical_or(a,b)
#Takes an array and returns the opposite of the Boolean values in the array
np.logical_not(a)

array([False,  True, False,  True])